version: '3.8'

services:
  multiversx-ai-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multiversx-ai-bot
    restart: unless-stopped
    ports:
      - "5000:5000"  # Web dashboard port
    volumes:
      - ./data:/app/data  # Persist data directory
      - ./.env:/app/.env  # Mount environment file
    environment:
      - PYTHONUNBUFFERED=1
      - NETWORK=${NETWORK:-devnet}  # Can be overridden with .env file
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Optional MongoDB for enhanced analytics storage
  mongodb:
    image: mongo:5.0
    container_name: multiversx-ai-bot-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
    env_file:
      - ./.env

volumes:
  mongodb_data: